apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - openshift-data-foundation-operator-subscription.yaml
  - openshift-data-foundation-operator-operatorgroup.yaml
