apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

bases:
  - ../ceph-patch/

resources:
  - cephobjectstore.yaml
  - ocsinitialization.yaml
  - rook-ceph-rgw-route.yaml
  - rook-ceph-rgw-service.yaml
