apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "5"

resources:
  - storagecluster-wait-job-rbac.yaml
  - storagecluster-wait-job-sa.yaml
  - storagecluster-wait-job.yaml
