apiVersion: batch/v1
kind: Job
metadata:
  name: storagecluster-wait-job
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/clo
              echo ""
              echo -n "Waiting for the storageclusters CRD to become available."
              sleep $SLEEP
              until oc wait --for condition=established --timeout=60s ${WAIT_RESOURCE} -n ${NAMESPACE}
              do
                echo -n "...still waiting"
                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: storagecluster-wait-job
          env:
          - name: WAIT_RESOURCE
            value: "crd/storageclusters.ocs.openshift.io"
          - name: NAMESPACE
            value: "openshift-storage"
          - name: SLEEP
            value: "5"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: storagecluster-wait-job-sa
      serviceAccountName: storagecluster-wait-job-sa
      terminationGracePeriodSeconds: 30
