apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-data-foundation-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: patch-me-see-overlays
    repoURL: patch-me-see-clusters-overlays
    targetRevision: patch-me-see-clusters-overlays
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
