apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators-applicationset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: amq-streams-operator
            path: components/operators/amq-streams/operator/overlays/stable
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: crunchy-postgres-operator
            path: components/operators/crunchy-postgres/operator/overlays/v5
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: opendatahub-operator
            path: components/operators/opendatahub/operator/overlays/stable
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: openshift-data-foundation-operator
            path: components/operators/openshift-data-foundation/aggregate/overlays/node-labeler
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: openshift-pipelines-operator
            path: components/operators/openshift-pipelines/operator/overlays/stable
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: openshift-serverless-operator
            path: components/operators/openshift-serverless/aggregate/knative-kafka
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: seldon-operator
            path: components/operators/seldon/operator/overlays/stable
        # - cluster: local
        #   url: https://kubernetes.default.svc
        #   values:
        #     name: quay-registry-operator
        #     path: components/operators/quay-registry/aggregate/overlays/default
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: cluster-config
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      source:
        repoURL: https://github.com/strangiato/cluster-bootstrap.git
        targetRevision: main
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
